services:
  bot:
    build:
      context: ./bot
      target: builder
    stop_signal: SIGINT
    container_name: bot
    env_file:
      - .env
    volumes:
      - shared:/shared
    depends_on:
      - yt_app
      - nginx

  yt_app:
    build: 
      context: ./yt_app
      target: builder
    stop_signal: SIGINT
    container_name: yt-app
    volumes:
      - shared:/shared
    ports:
      - "5000:5000"

  nginx: 
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      #- ./nginx/conf.d/audio.conf:/etc/nginx/conf.d/audio.conf
      - ./nginx/conf.d/video.conf:/etc/nginx/conf.d/video.conf
      - ./nginx/htdocs/video.html:/usr/share/nginx/html/video.html
      - shared:/usr/share/nginx/html/hls
    ports:
      - "80:80"
      - "443:443"

  icecast:
    build: ./icecast
    container_name: icecast
    ports:
      - "8000:8000"
    volumes:
      - shared:/shared

volumes:
  shared: