services:
  dyndns:
    build:
      context: ./dyndns
      dockerfile: Dockerfile
    container_name: dyndns
    restart: unless-stopped
    depends_on:
      - nginx

  bot:
    build:
      context: ./bot
      target: builder
    stop_signal: SIGINT
    container_name: bot
    env_file:
      - .env
    volumes:
      - shared:/shared
    depends_on:
      - yt_app
      - nginx

  yt_app:
    build: 
      context: ./yt_app
      target: builder
    stop_signal: SIGINT
    container_name: yt-app
    volumes:
      - shared:/shared

  nginx: 
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htdocs/video/index.html:/usr/share/nginx/html/video/index.html
      - ./nginx/htdocs/index.html:/usr/share/nginx/html/index.html
      - shared:/usr/share/nginx/html/hls
      - certs:/etc/letsencrypt
    ports:
      - "8080:80"
      - "4433:443"

  icecast:
    image: libretime/icecast
    container_name: icecast
    restart: unless-stopped
    volumes:
      - ./icecast/icecast.xml:/etc/icecast.xml
      - ./icecast/logs/error.log:/var/log/icecast2/error.log
      - ./icecast/logs/access.log:/var/log/icecast2/access.log
      - shared:/shared

  ices2:
    build: 
      context: ./ices2
      dockerfile: Dockerfile 
    container_name: ices2
    restart: unless-stopped
    depends_on:
      - icecast
    volumes:
      - shared:/shared

volumes:
  shared:
  certs:
    external: true