name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r yt_app/requirements.txt
        pip install -r bot/requirements.txt
        pip install pytest pytest-asyncio

    - name: Run tests
      env:
        SHARED_VOLUME: /tmp/shared
      run: |
        pytest yt_app/tests/ -v
        pytest bot/tests/ -v